# Generated by Django 2.2 on 2019-04-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=15)),
                ('movie_data', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
